version: "3"

services:
  application:
    image: template_root
    container_name: template_root
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8345:8000"
    volumes:
      - ./src:/app:cached
    depends_on:
      - mysql
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    networks:
      - backend

  mysql:
    container_name: template_mysql
    build: ./docker/mysql/
    env_file: docker/mysql/conf/env.yml
    ports:
      - "3620:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - template_mysql:/data/mysql
    networks:
      - backend

volumes:
  template_mysql:

networks:
  backend: